name: Packer Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build with Packer
      run: |
        docker run -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} -v $(pwd):/workspace -w /workspace hashicorp/packer:latest sh -c "packer init ./packer/aws-ubuntu.pkr.hcl && packer validate ./packer/aws-ubuntu.pkr.hcl && packer build ./packer/aws-ubuntu.pkr.hcl"
